# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
Vec10=np.empty(10)
Vec10[:]=np.NaN
print(Vec10)

[nan nan nan nan nan nan nan nan nan nan]


3. Create a vector with values ranging from 10 to 49

In [3]:
Vec10To49=np.array(range(10))

4. Find the shape of previous array in question 3

In [4]:
print("Size of the array: ", Vec10To49.size)

Size of the array:  10


5. Print the type of the previous array in question 3

In [5]:
print(Vec10To49)

[0 1 2 3 4 5 6 7 8 9]


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ThisPC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/ThisPC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ThisPC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

7. Print the dimension of the array in question 3


In [7]:
print(Vec10To49.ndim)

1


8. Create a boolean array with all the True values

In [8]:
MyboolArray=np.ones((1, 4), dtype=bool)
print(MyboolArray)

[[ True  True  True  True]]


9. Create a two dimensional array




In [9]:
My2DArray= np.random.randn(2, 3)
print(My2DArray)

[[-1.30275038  0.00962017 -0.99415421]
 [-0.46555946  1.65547409  0.60748977]]


10. Create a three dimensional array



In [10]:
My3DArray= np.random.randn(2, 3,5)
print(My3DArray)

[[[ 1.23621971  0.50578932 -0.27225927  0.10642346 -0.75641073]
  [-1.50380255  0.14894249 -0.43447745  2.12954246  0.7463046 ]
  [-0.16503707 -0.16732516  1.39891947  1.36315545 -0.55054426]]

 [[-1.06272382  0.865411    1.04497237  0.15043354  2.85172071]
  [-0.88652955 -0.91700442 -1.07142797  0.83240698 -2.38260519]
  [ 0.56021229  0.74078692 -0.2214524  -1.01313544  0.49589701]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
d= np.array([1,2,3,4,5,6])
print(d[::-1])

[6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
NArray=np.empty(10)
NArray[4]=1

print(NArray)

[1.25474290e-311 2.07507571e-322 0.00000000e+000 0.00000000e+000
 1.00000000e+000 1.16096346e-028 1.04857803e-142 1.16467185e-028
 1.50105153e-153 4.10114146e+223]


13. Create a 3x3 identity matrix

In [13]:
Identity3d =np.identity(3)
print(Identity3d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr2-arr1)

[[-1.  2. -2.]
 [ 3. -3.  6.]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    print(NumArray[i])

[0 1 2 3 4 5 6 7 8 9]
1
3
5
7
9


18. Replace all odd numbers to -1 from previous array

In [18]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    NumArray[i]=-1
print(NumArray)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
print(arr)


[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
length=4
height=5
BorderArray= (np.ones((height,length)))
BorderArray[1:height-1,1:length-1]=0
print(BorderArray)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.where(arr2d==5, 12, arr2d)) 


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(np.where(arr3d>=0, 64, arr3d)) 

[[[64 64 64]
  [64 64 64]]

 [[64 64 64]
  [64 64 64]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
FirstRow=(Array2D[0,:3 ])
print(FirstRow)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
Second2nd=(Array2D[1,1])
print(Second2nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
ThridCol2Val=(Array2D[0:2, 2])
print(ThridCol2Val)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum 

---

values

In [26]:
Ten10Arr = np.random.randint(100, size=(10, 10))
print(Ten10Arr)
print(np.min(Ten10Arr))
print(np.max(Ten10Arr))


[[51 45 60 58 81 47 13 74 11 46]
 [60 84  5 19 28  7 49 91 88  4]
 [73 78 82  6 90 66 56 56 25 45]
 [24 10 42 30 10  9 48 80 14 21]
 [45 46 96 69 88 47 21 70 35 45]
 [31 27 25 84 53 22 38 17 49  8]
 [83 48 81 58 90 68 79 10 38 33]
 [29  6 57 39 99  6  9 92 63 95]
 [82 50 12 99 11 14 49 43 97 69]
 [21 87 80 20 35 47 43 52 63 14]]
4
99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key, val in enumerate(a) if val in set(b)])


[1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Indeces where name is not Will : ", np.where(names!="Will"))

print("Values : ",names[np.where(names!="Will")])


Indeces where name is not Will :  (array([0, 1, 3, 5, 6], dtype=int64),)
Values :  ['Bob' 'Joe' 'Bob' 'Joe' 'Joe']


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)

mask=(names2!="Will")&(names2!="Joe")
data[mask]


[[-0.21364844 -0.23768455 -1.99455715 -1.4652638 ]
 [-1.08449677  0.29656936  1.18207739 -0.80586916]
 [-0.21707115  1.00239377  0.20841317  1.29804314]
 [-0.13246795 -1.22027492  0.32654253  0.21762948]
 [ 0.60967072 -0.70381357 -0.26552319  1.92807293]
 [ 0.87775015 -0.53704463 -0.35832411 -0.08127827]
 [-0.63122979 -0.22182212 -0.18753207 -0.34228234]]


array([[-0.21364844, -0.23768455, -1.99455715, -1.4652638 ],
       [-0.13246795, -1.22027492,  0.32654253,  0.21762948]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
TwoDArray = np.array(range(1,16), dtype=np.float64).reshape(5,3)
print(TwoDArray)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]



32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
ThreeDArray = np.array(range(1,17), dtype=np.float64).reshape(2,2,4)
print(ThreeDArray)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [33]:
ThreeDArray.reshape(4,2,2)

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:

SQARTArray = np.sqrt(abs(np.random.randn(10)))
print(SQARTArray)
RemoveingLessThanHalf=np.where(SQARTArray<0.5,0,SQARTArray)
print(RemoveingLessThanHalf)

[0.96029502 0.36036836 0.16907985 0.154553   1.17795388 0.435254
 0.79327201 0.50499314 0.35008009 0.91921852]
[0.96029502 0.         0.         0.         1.17795388 0.
 0.79327201 0.50499314 0.         0.91921852]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
RandomArray1=np.random.randint(12, size=(1, 12))[0]
RandomArray2=np.random.randint(12, size=(1, 12))[0]
MaxArr=np.maximum(RandomArray1,RandomArray2)

print("Array1 :",RandomArray1)
print("Array2 :",RandomArray2)
print("Maximum of two:", MaxArr)


Array1 : [ 4  7  4 11  0  6  2  2  6 10  2 11]
Array2 : [ 0  2  8  2  8  3  6  5  1 11  8  7]
Maximum of two: [ 4  7  8 11  8  6  6  5  6 11  8 11]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
from collections import Counter

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

ca = Counter(a)
cb = Counter(b)

result_a = sorted((ca - cb).elements())

print(result_a)


[1, 2, 3, 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
for i in range(3):
  sampleArray[i,1]=newColumn[0,i]

print(sampleArray)



[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=x.reshape(1,6)*y.reshape(1,6)
print(z)

[[ 6. 46. -3. 28. 40. 54.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
Arr20 = np.random.randint(20, size=(5, 4))
print(Arr20)
print("Sum of All Numbers : ",np.sum(Arr20))

[[11  7 17 14]
 [ 0  5  9  9]
 [ 6  2  6  1]
 [ 5  9 15 12]
 [18  7 10 16]]
Sum of All Numbers :  179
