# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
Vec10=np.empty(10)
print(Vec10)

[3.1452393e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000]


3. Create a vector with values ranging from 10 to 49

In [ ]:
Vec10To49=np.array(range(10))

4. Find the shape of previous array in question 3

In [ ]:
print("Size of the array: ", Vec10To49.size)

Size of the array:  10


5. Print the type of the previous array in question 3

In [ ]:
print(Vec10To49)

[0 1 2 3 4 5 6 7 8 9]


6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [ ]:
print(Vec10To49.ndim)

1


8. Create a boolean array with all the True values

In [ ]:
MyboolArray=np.ones((1, 4), dtype=bool)
print(MyboolArray)

[[ True  True  True  True]]


9. Create a two dimensional array




In [ ]:
My2DArray= np.random.randn(2, 3)
print(My2DArray)

[[-0.30690298 -1.51553447  0.47116515]
 [ 0.78435    -1.20697097  2.28471088]]


10. Create a three dimensional array



In [ ]:
My3DArray= np.random.randn(2, 3,5)
print(My3DArray)

[[[-0.15442241 -0.06040139  1.07567847  1.33366131 -0.18524168]
  [ 1.30147761 -0.67066602 -0.12208098  0.20340468 -0.54033262]
  [ 0.02073007  1.04746788  0.73623434  0.99235128 -0.38141186]]

 [[ 0.19204934  0.62653641  0.31419033  1.34580697 -0.16460668]
  [ 0.37231083 -0.85668265 -0.08233973  2.22948354  1.37811682]
  [-0.12421453  1.57573492  0.13567025  1.79283552 -0.33574119]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [4]:
d= np.array([1,2,3,4,5,6])
print(d.flip())

AttributeError: ignored

12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
NArray=np.empty(10)
NArray[4]=1

print(NArray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [ ]:
Identity3d =np.identity(3)
print(Identity3d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr2-arr1)

[[-1.  2. -2.]
 [ 3. -3.  6.]]


17. Extract all odd numbers from arr with values(0-9)

In [ ]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    print(NumArray[i])

[0 1 2 3 4 5 6 7 8 9]
1
3
5
7
9


18. Replace all odd numbers to -1 from previous array

In [ ]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    NumArray[i]=-1
print(NumArray)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
print(arr)


[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [9]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.where(arr2d==5, 12, arr2d)) 


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [11]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(np.where(arr3d>=0, 64, arr3d)) 

[[[64 64 64]
  [64 64 64]]

 [[64 64 64]
  [64 64 64]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [33]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
FirstRow=(Array2D[0,:3 ])
print(FirstRow)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [37]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
Second2nd=(Array2D[1,1])
print(Second2nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
ThridCol2Val=(Array2D[0:2, 2])
print(ThridCol2Val)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum 

---

values

In [45]:
Ten10Arr = np.random.randint(100, size=(10, 10))
print(Ten10Arr)
print(np.min(Ten10Arr))
print(np.max(Ten10Arr))


[[13 57 38 74 10 63  2 71 54 77]
 [90  6 17 23 15 95 64 41 22 86]
 [96 92 17 36 39 22 42 38 96  3]
 [73 86 46 93 88 79  8 12 81 76]
 [ 6 97 50 31 44 92 18 52 94 31]
 [14 65 67 36  1 34 86  7 22 94]
 [81 45  5 40 71 71 37 74 68 68]
 [39  1 11 57 19 47 80 60 71 73]
 [53 78 68 61 52 71 87 84 93 80]
 [83 35 49 15 32 91 28  6 84  6]]
1
97


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key, val in enumerate(a) if val in set(b)])


[1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Indeces where name is not Will : ", np.where(names!="Will"))

print("Values : ",names[np.where(names!="Will")])


Indeces where name is not Will :  (array([0, 1, 3, 5, 6]),)
Values :  ['Bob' 'Joe' 'Bob' 'Joe' 'Joe']


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [76]:
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Indeces where name is not Will : ", np.where((names2!="Will")&( names2!="Joe"))[0])

print("Values : ",names[np.where((names2!="Will")&( names2!="Joe"))[0]])


Indeces where name is not Will :  [0 3]
Values :  ['Bob' 'Bob']


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [88]:
TwoDArray = np.array(range(1,16), dtype=np.float64).reshape(5,3)
print(TwoDArray)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]



32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [91]:
ThreeDArray = np.array(range(1,17), dtype=np.float64).reshape(2,2,4)
print(ThreeDArray)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [92]:
ThreeDArray.reshape(4,2,2)

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [99]:

SQARTArray = np.sqrt(abs(np.random.randn(10)))
print(SQARTArray)
RemoveingLessThanHalf=np.where(SQARTArray<0.5,0,SQARTArray)
print(RemoveingLessThanHalf)

[1.2089942  1.42233091 0.39295055 0.57048281 0.44828839 0.67700128
 0.43595954 0.61176526 1.15112597 1.0019092 ]
[1.2089942  1.42233091 0.         0.57048281 0.         0.67700128
 0.         0.61176526 1.15112597 1.0019092 ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [128]:
RandomArray1=np.random.randint(12, size=(1, 12))[0]
RandomArray2=np.random.randint(12, size=(1, 12))[0]
MaxArr=np.maximum(RandomArray1,RandomArray2)

print("Array1 :",RandomArray1)
print("Array2 :",RandomArray2)
print("Maximum of two:", MaxArr)


Array1 : [1 5 5 4 3 3 5 8 9 2 9 6]
Array2 : [ 7  3  2  5  1  4  4  8  1  8 10  7]
Maximum of two: [ 7  5  5  5  3  4  5  8  9  8 10  7]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!


In [132]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [134]:
from collections import Counter

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

ca = Counter(a)
cb = Counter(b)

result_a = sorted((ca - cb).elements())

print(result_a)


[1, 2, 3, 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [137]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
for i in range(3):
  sampleArray[i,1]=newColumn[0,i]

print(sampleArray)



[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=x.reshape(1,6)*y.reshape(1,6)
print(z)

[[ 6. 46. -3. 28. 40. 54.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [141]:
Arr20 = np.random.randint(20, size=(5, 4))
print(Arr20)
print("Sum of All Numbers : ",np.sum(Arr20))

[[10  0 11  3]
 [18 16 17  8]
 [ 6 16  9 16]
 [ 4 17 12  5]
 [ 3 11 12  4]]
Sum of All Numbers :  198
